{
    "name": "Syscraft Clinic Management System",
    "author": "Joe",
    'version': '1.0',
    'category': 'Health',
    'sequence': 1,
    "website": "localhost:8071/clinic",
    "depends": ["mail", "sale", "account"],
    "data": [

        "security/ir.model.access.csv",
        "data/prescription_mail_template.xml",
        "data/quotation_mail_template.xml",
        "data/appointment_sequence.xml",
        "data/snippet_currency_chart_data.xml",
        # "wizard/past_emr.xml",
        "wizard/medical_summary_view.xml",

        "views/menu.xml",
        # "views/sysCMS.xml",
        "views/sys-calendar.xml",
        "views/investigations.xml",
        "views/investigations-in-tray.xml",
        "views/investigations-collect-sample.xml",
        "views/invetigations-bill-order.xml",
        "views/investigations-record-result.xml",
        "views/investigations-follow-up.xml",
        "views/patients.xml",
        "views/patient_document_view.xml",
        "views/pharmacy.xml",
        "views/financials.xml",
        "views/financial-bill.xml",
        "views/financial-custom-package.xml",
        "views/financial-package.xml",
        "views/financial-quotation.xml",
        "views/financial-expense.xml",
        "views/financial-refund.xml",
        "views/inventory.xml",
        "views/inventory-stock-order.xml",
        "views/tools.xml",
        "views/tool_investigation.xml",
        "views/documents.xml",
        "views/addressbook.xml",
        "views/appointment_template_view.xml",
        "views/clinical_group_view.xml",
        "views/clinical-item-parameters.xml",
        "views/holiday.xml",
        "views/dropdowns.xml",
        "views/pending_signing_view.xml",
        "views/print_queue.xml",
        "views/snippet_currency_chart_template.xml",
        "views/snippet_currency_chart_view.xml",
        "views/paper_work_view.xml",
        "views/library.xml",
        "views/immunisations-schedule.xml",
        "report/pharmacy_report.xml",
        "report/quotation_report.xml"
    ],

    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': ['static/src/xml/*.xml'],
    'web_dashboard': 'SyscraftClinicManagement.203',
}
